	graph <*graph*>
	{
		<*graph+rule_id*>> a rules_ont:Rule;
        <*triger*>
		<*result*>
		<*graph+rule_id*>> rules_ont:hasPreferenceValue <*preference_value*>;
		<*graph+rule_id*>> rules_ont:hasContent <*content*>;
	}